---
name: Build Artifact

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*.*
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Generate Artifact
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compress and Generate Archive
        run: |
          echo 'Hello, World!' >> message.txt
          zip -r ${{ github.workspace }}/devtools.zip message.txt

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp \
            ${{ github.workspace }}/devtools.zip \
            ${{ github.workspace }}/devtools-${{ github.ref_name }}.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1.11.2
        with:
          allowUpdates: true
          prerelease: true
          artifacts: |
            ${{ github.workspace }}/devtools-${{ github.ref_name }}.zip
