---
name: Build Artifact

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*.*
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Generate Artifact
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Environment Variables
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "APP_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "APP_VERSION=x.x.x" >> $GITHUB_ENV
          fi

      - name: Compress and Generate Archive
        run: |
          echo 'Hello, Galaxy!' >> message.txt
          echo 'Commit: ${{ github.sha }}' >> message.txt
          echo "Version: $APP_VERSION" >> message.txt
          zip -r ${{ github.workspace }}/devtools.zip message.txt

      - name: Prepare Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp \
            ${{ github.workspace }}/devtools.zip \
            ${{ github.workspace }}/devtools-${{ github.ref_name }}.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1.11.2
        with:
          allowUpdates: true
          prerelease: true
          artifacts: |
            ${{ github.workspace }}/devtools-${{ github.ref_name }}.zip
          commit: ${{ github.sha }}
